// dummydata
const products = [
  {
    id: "1",
    manufacturerId: "1",
    name: "Easy ceiling general lighting",
    type: ["downlight"],
    mounting: ["surface"],
    ip: ["40"],
    bodyColour: ["white", "black"],
    beamAngles: [66],
    colourTemp: [3000, 4000],
    cri: [80, 90],
    length: 114,
    width: 114,
    height: 155,
    diameter: 114,
    recessDepth: 0,
  },
  {
    id: "2",
    manufacturerId: "2",
    name: "Logic Mini W S",
    type: ["steplight"],
    mounting: ["recessed"],
    ip: ["54"],
    bodyColour: ["grey", "white"],
    beamAngles: [120],
    colourTemp: [3000],
    cri: [80],
    length: 62,
    width: 40,
    height: 62,
    recessDepth: 36,
  },
  {
    id: "3",
    manufacturerId: "3",
    name: "Lumenbeam Small",
    type: ["spotlight"],
    mounting: ["surface"],
    ip: ["66"],
    bodyColour: ["black", "grey", "white", "bronze", "green", "custom"],
    beamAngles: [4, 6, 10, 20, 30, 40, 60],
    colourTemp: [2200, 2700, 3000, 3500, 4000, 5700],
    cri: [80],
    length: 118,
    width: 138,
    height: 213,
    diameter: 135,
    recessDepth: 0,
  },
  {
    id: "4",
    manufacturerId: "1",
    name: "Easy ceiling general lighting",
    type: ["downlight"],
    mounting: ["surface"],
    ip: ["40"],
    bodyColour: ["white", "black"],
    beamAngles: [13],
    colourTemp: [4000],
    cri: [80, 90],
    length: 300,
    width: 20,
    height: 155,
    diameter: 114,
    recessDepth: 0,
  },
  {
    id: "5",
    manufacturerId: "1",
    name: "Super Narrow Spot",
    type: ["spotlight"],
    mounting: ["recessed"],
    ip: ["20"],
    bodyColour: ["white"],
    beamAngles: [6],
    colourTemp: [2700, 3000],
    cri: [80, 90],
    length: 50,
    width: 50,
    height: 150,
    diameter: 50,
    recessDepth: 0,
  },
];

const manufacturers = [
  {
    id: "1",
    name: "iGuzzini",
    country: "Italy",
    website: "https://www.iguzzini.com/",
  },
  {
    id: "2",
    name: "Delta Light",
    country: "Belgium",
    website: "https://www.deltalight.com/",
  },
  {
    id: "3",
    name: "Lumenpulse",
    country: "Canada",
    website: "https://www.lumenpulse.com/",
  },
];

module.exports = { products, manufacturers };
