// dummydata
const products = [
  {
    id: "1",
    manufacturerId: "1",
    name: "Easy ceiling general lighting",
    type: "Downlight",
    mounting: "Surface",
    ip: ["40"],
    bodyColour: ["White", "Black"],
    length: 114,
    width: 114,
    height: 155,
    diameter: 114,
    recessDepth: 0,
    beamAngle: [66],
    colourTemp: [3000, 4000],
    cri: [80, 90],
  },
  {
    id: "2",
    manufacturerId: "2",
    name: "Logic Mini W S",
    type: "Steplight",
    mounting: "Recessed",
    ip: ["54"],
    bodyColour: ["Grey", "White"],
    length: 62,
    width: 40,
    height: 62,
    diameter: null,
    recessDepth: 36,
    beamAngle: [120],
    colourTemp: [3000],
    cri: [80],
  },
  {
    id: "3",
    manufacturerId: "3",
    name: "Lumenbeam Small",
    type: "Spotlight",
    mounting: "Surface",
    ip: ["66"],
    bodyColour: ["Black", "Grey", "White", "Bronze", "Green", "Custom RAL"],
    length: 138,
    width: 118,
    height: 213,
    diameter: 135,
    recessDepth: 0,
    beamAngle: [4, 6, 10, 20, 30, 40, 60],
    colourTemp: [2200, 2700, 3000, 3500, 4000, 5700],
    cri: [80],
  },
  {
    id: "4",
    manufacturerId: "1",
    name: "Easy ceiling general lighting",
    type: "Downlight",
    mounting: "Surface",
    ip: ["40"],
    bodyColour: ["White", "Black"],
    length: 114,
    width: 114,
    height: 155,
    diameter: 114,
    recessDepth: 0,
    beamAngle: [66],
    colourTemp: [4000],
    cri: [80, 90],
  },
];

const manufacturers = [
  {
    id: "1",
    name: "iGuzzini",
    country: "Italy",
    website: "https://www.iguzzini.com/",
  },
  {
    id: "2",
    name: "Delta Light",
    country: "Belgium",
    website: "https://www.deltalight.com/",
  },
  {
    id: "3",
    name: "Lumenpulse",
    country: "Canada",
    website: "https://www.lumenpulse.com/",
  },
];

module.exports = { products, manufacturers };
